#!/usr/bin/env node

var path = require('path'),
	fs = require('fs'),
	util = require('util');

var validConfig = function (config) {

	return config
		&& config.token === 'token'
		&& config.subdomain === 'subdomain';

};

var loadConfig = function () {

	try {

		var config = require('../../test/test-config.json');

		if (!validConfig(config)) {
			util.puts('\nConfig file test-config.json must be return to the default (i.e. remove your specific loggly values)');
			process.exit(1);
		}

		process.exit(0);

	} catch (e) {

		util.puts('Error parsing test-config.json');
		e.stack.split('\n').forEach(function (line) {
			util.puts(line)
		});

		process.exit(1);

	}

};

// run the tests
loadConfig();